# Generated by Django 2.0.1 on 2018-07-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20180723_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='total',
            new_name='valor',
        ),
    ]
