# Generated by Django 2.0.1 on 2018-07-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20180723_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parâmetro NF-E'), ('permissao2', 'Permissao2'), ('permissao3', 'Permissao3'))},
        ),
    ]
