# Generated by Django 2.0.1 on 2018-07-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20180720_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='valor',
            new_name='total',
        ),
    ]
