# Generated by Django 2.0.1 on 2018-07-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20180723_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Deleta um cliente'),)},
        ),
    ]
